/*
            MUST:
1. ADD STATUSES FOR CURSES AND BONUSES  <- ACTUALLY HERE

2. ADD SOME EXTRA MOVEMENTS FOR PLAYER

3. ANIMATE MENU WITH BALLS

4. IMPROVE LOGIC OF CURSE AND BONUS

5. ADD CLOCK OF PLAYTIME

6. ADD SCORE OF PLAYTIME

7. ADD TABLE OF HICHSCORE

8. ADD ASSETS OF PLAYER

9. ADD ABILITY TO CHANGE PLAYER MODEL

10. ADD ADJUSTABLE SCREEN

//11. MOVE VARIABLES IN CLASSES, IF IT CAN BE MOVED
 
            MAYBE:
  IMPROVE LOGIC OF BALLS THAT THEY CAN MOVE MORE RANDOBLY

  RANDOM WALLS (RANDOM TIME)
*/
